from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import StreamingResponse
from datetime import datetime, timezone
from pathlib import Path
import uuid
import logging
import zipfile
import io
import os

from database import db
from models import User
from deps import get_current_user

router = APIRouter(prefix="/mobile-app", tags=["mobile-app"])


@router.post("/generate")
async def generate_mobile_app(user: User = Depends(get_current_user)):
    store = await db.stores.find_one({"user_id": user.user_id}, {"_id": 0})
    if not store:
        raise HTTPException(status_code=404, detail="Store not found")

    try:
        from utils.flutter_generator import FlutterAppGenerator

        generator = FlutterAppGenerator(store)
        files = generator.generate_all_files()

        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
            for file_path, content in files.items():
                zip_file.writestr(file_path, content)
            zip_file.writestr('PUBLISHING_GUIDE.md', _publishing_guide(store))
            zip_file.writestr('lib/screens/product_detail_screen.dart', _product_detail_screen())
            zip_file.writestr('lib/screens/cart_screen.dart', _cart_screen())
            zip_file.writestr('assets/images/.gitkeep', '')

        zip_buffer.seek(0)

        app_record = {
            "app_id": f"app_{uuid.uuid4().hex[:12]}",
            "store_id": store["store_id"],
            "package_name": generator.package_name,
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "version": "1.0.0"
        }
        await db.mobile_apps.insert_one(app_record)

        return StreamingResponse(
            zip_buffer,
            media_type="application/zip",
            headers={"Content-Disposition": f"attachment; filename={store['store_name'].replace(' ', '_')}_app.zip"}
        )
    except Exception as e:
        logging.error(f"Mobile app generation error: {e}")
        raise HTTPException(status_code=500, detail=f"Failed to generate app: {str(e)}")


@router.get("/status")
async def get_mobile_app_status(user: User = Depends(get_current_user)):
    store = await db.stores.find_one({"user_id": user.user_id}, {"_id": 0})
    if not store:
        raise HTTPException(status_code=404, detail="Store not found")

    app = await db.mobile_apps.find_one({"store_id": store["store_id"]}, {"_id": 0})

    return {
        "has_app": app is not None,
        "app_data": app if app else None,
        "package_name": f"com.shopswift.{store['subdomain'].lower().replace('-', '').replace('_', '')}",
        "app_name": store["store_name"]
    }


def _publishing_guide(store):
    package_name = f"com.shopswift.{store['subdomain'].lower().replace('-', '').replace('_', '')}"
    return f"""# Publishing Guide - {store['store_name']} Mobile App

## App Details
- App Name: {store['store_name']}
- Package Name: {package_name}
- Store ID: {store['store_id']}
- Version: 1.0.0

## Build Instructions

### Build Android APK
```bash
flutter pub get
flutter build apk --release
```

### Build iOS IPA
```bash
flutter build ios --release
open ios/Runner.xcworkspace
```

## Centralized Publishing

### Google Play Store
- Published under: ShopSwift India (centralized account)

### Apple App Store
- Published under: ShopSwift India (centralized account)

Generated by ShopSwift India
"""


def _product_detail_screen():
    return """import 'package:flutter/material.dart';

class ProductDetailScreen extends StatelessWidget {
  final dynamic product;
  const ProductDetailScreen({required this.product});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Product Details')),
      body: Text(product['name'] ?? ''),
    );
  }
}
"""


def _cart_screen():
    return """import 'package:flutter/material.dart';

class CartScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Shopping Cart')),
      body: Center(child: Text('Cart is empty')),
    );
  }
}
"""
